Main page dark mode
sarmadhamdani02/WebGames pull request #37
Opened 2023-08-21 00:40 UTC by MRodriguez-M

Implemented feature so that the main page has a toggle option for dark mode. Addresses issue #10

2023-08-21 17:24 UTC, sarmadhamdani02 requested changes

2023-08-21 17:24 UTC, sarmadhamdani02 commented on main.css
> +:root {
I believe placing the variables at the beginning of the CSS file would be a better approach. Additionally, using more descriptive names for the variables would enhance the code's readability, especially for new contributors, including beginners. And if I am not getting this wrong this `background-color` is for the toggle button's background color 🤔 if so, naming it as `toggleBtn-background-color` will be a better approach.

2023-08-21 17:24 UTC, sarmadhamdani02 commented on script.js
> +    }
I think the color `#121212` is too dark. Adding a bit less dark color like `#212628` will look much more appealing. Try playing with a bit less dark colors and change it if you feel like it.

2023-08-21 17:24 UTC, sarmadhamdani02 commented on script.js
> +    }
Apart from this, I think everything is amazing 👏👏

2023-08-22 14:31 UTC, sarmadhamdani02 commented
Thank you so much @MRodriguez-M  for the great work 👏👏

2023-08-22 14:34 UTC, merged

2023-08-22 16:54 UTC, MRodriguez-M commented
> Hey @MRodriguez-M 👋
> 
> I've recently opened a new issue regarding the dark mode feature. It appears that after implementing the dark mode, the responsiveness of the Navbar has been affected. As no one knows the dark mode code better than you, I thought you might be the best person to take a look at issue #41, if you're available.
> 
> I know that you are already working on other issues so if you don't want to do that. There is absolutely no problem. 😊
> 
> Regards.

Yeah, I can take care of that. When building the dark mode feature, I didn't fully take responsiveness into account so now's a great time to do it. I'll go leave a message on the issue so it can be assigned to me